version: "3.9"

services:
  worker:
    build: .
    restart: always
    environment:
      REDIS_HOST: 65.108.92.223
      REDIS_PORT: 6379
      REDIS_PASSWORD: "raiv2010"
      PLUG4MARKET_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb2Z0d2FyZUhvdXNlIjoiMzkyNzM4NDEwMDAxMDgiLCJzdG9yZSI6IjM3NTc4ODI1MDAwMTA2IiwidXJsIjoiYXBpLnBsdWc0bWFya2V0LmNvbS5iciIsInVzZXJJZCI6ImRhNDE1ZmY1LWRhNDItNDU5Yi04N2M2LTdhY2U2YmQzYWI1NiIsInJlZnJlc2hUb2tlbiI6ImRhMTBjODZmZjhiNjA4MjkzMzJmZTA3YzE2ODk0OGU3NTIxNjJmYWIyNTc2ZmFhZThkOWNhZGIzMTM3NTZmNDMiLCJ0eXBlIjoic3RvcmUiLCJpYXQiOjE3NjM2Mjg1NDYsImV4cCI6MTc2MzcxNDk0Nn0.hFMoqR6uuYz2KiRzVx8VHI4pO0EPp0OBUo9uaVH3rlo"
      WEBHOOK_URL: "https://webhook.site/5472f4ff-318a-4771-8e7f-55cbe3bbc832"